# This is a basic workflow to help you get started with Actions

name: MinGW

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    # set environment variables
    env:
      MSYSTEM: MINGW64
      MSYSTEM_PREFIX: /mingw64
      MSYS2_ARCH: x86_64
      CHOST: "x86_64-w64-mingw32"
      CFLAGS:   "-march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong"
      CXXFLAGS: "-march=x86-64 -mtune=generic -O3 -pipe"
      CPPFLAGS: "-D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048"
      LDFLAGS:  "-pipe -fstack-protector-strong"
      UPDATE_UNICODE: "UNICODE_FILES=. UNICODE_PROPERTY_FILES=. UNICODE_AUXILIARY_FILES=. UNICODE_EMOJI_FILES=."

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: find / -name time.h
      shell: bash

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo compile main.c
        gcc --version
        gcc main.c
        ls .
      shell: bash
      
    # Runs a compiled program
    - name: Run a compiled program
      run: |
        export PATH=".:/bin:$PATH"
        echo $PATH
        ls .
        a.exe
      shell: bash
